//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSignage.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackgroundImageStorage
    {
        public int ImageId { get; set; }
        public string ImageName { get; set; }
        public string Opacity { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> ImageStatus { get; set; }
        public string DisplayContent { get; set; }
    }
}
