//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSignage.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public int CampaignId { get; set; }
        public string CampaignName { get; set; }
        public Nullable<int> DisplayId { get; set; }
        public Nullable<int> SceneId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string Frequency { get; set; }
        public Nullable<bool> Published { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Interval { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string DeviceGroup { get; set; }
        public string Zone { get; set; }
        public string DaysOfWeek { get; set; }
    }
}
