//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSignage.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceContentTracker
    {
        public int TrackerId { get; set; }
        public int DeviceId { get; set; }
        public string PlayerSerialNo { get; set; }
        public int DisplayId { get; set; }
        public int SceneId { get; set; }
        public int CampaignId { get; set; }
        public string ContentUrl { get; set; }
        public string Content { get; set; }
        public string ContentType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string Frequency { get; set; }
        public Nullable<bool> Published { get; set; }
        public string Status { get; set; }
        public Nullable<int> ShedulerId { get; set; }
        public Nullable<int> MessageId { get; set; }
        public Nullable<int> Interval { get; set; }
        public string TemplateType { get; set; }
        public string IconPosition { get; set; }
        public Nullable<System.DateTime> ActionTime { get; set; }
        public string Action { get; set; }
        public string Zone { get; set; }
        public string DaysOfWeek { get; set; }
    }
}
