//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSignage.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceContentHistory
    {
        public int TranId { get; set; }
        public int DeviceId { get; set; }
        public int DisplayId { get; set; }
        public int SceneId { get; set; }
        public int CampaignId { get; set; }
        public string ContentUrl { get; set; }
        public string ContentType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public int Interval { get; set; }
        public string Status { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedTime { get; set; }
    }
}
