//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSignage.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaceRecogSignage
    {
        public int Id { get; set; }
        public Nullable<int> AgeLowerLimit { get; set; }
        public Nullable<int> AgeUpperLimit { get; set; }
        public string Gender { get; set; }
        public string Signage { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string SceneType { get; set; }
        public Nullable<int> Duration { get; set; }
    }
}
