//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSignage.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scene
    {
        public int SceneId { get; set; }
        public string SceneName { get; set; }
        public string SceneUrl { get; set; }
        public string SceneContent { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsPrimaryApproved { get; set; }
        public string SceneType { get; set; }
        public string Status { get; set; }
        public Nullable<int> Approver { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string TemplateType { get; set; }
        public string IconPosition { get; set; }
    }
}
