//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSignage.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignageBIView
    {
        public int CampaignId { get; set; }
        public string CampaignName { get; set; }
        public int DisplayId { get; set; }
        public string DisplayName { get; set; }
        public int PlayerId { get; set; }
        public string PlayerName { get; set; }
        public int DeviceId { get; set; }
        public int SceneId { get; set; }
        public string SceneName { get; set; }
        public string Status { get; set; }
    }
}
