//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSignage.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWDevicewithGroup
    {
        public int PlayerId { get; set; }
        public string PlayerSerialNo { get; set; }
        public string PlayerName { get; set; }
        public string GroupName { get; set; }
        public int GroupId { get; set; }
        public string GroupType { get; set; }
    }
}
